In [145]:
import pandas as pd
print(pd.__version__)

2.2.2

In [146]:
a1 = [3,5,-1,4]
s1 = pd.Series(a1)
print(s1)
print(type(s1), s1.dtype)
print(s1.index)

0    3
1    5
2   -1
3    4
dtype: int64
<class 'pandas.core.series.Series'> int64
RangeIndex(start=0, stop=4, step=1)

In [147]:
b1 = ['a','b','c','d']
b2 = ['가','나','다','라']

s2 = pd.Series(b1, index=b2)
print(s2)
print(type(s2), s2.dtype)
print(s2.index)

가    a
나    b
다    c
라    d
dtype: object
<class 'pandas.core.series.Series'> object
Index(['가', '나', '다', '라'], dtype='object')

In [148]:
c2 = {'name': ['Jane','Tom','Alice','Hong'],
      'age':[34,24,51,45],
      'point':[80,70,90,100]}
s4 = pd.Series(c2)
print(s4)

name     [Jane, Tom, Alice, Hong]
age              [34, 24, 51, 45]
point           [80, 70, 90, 100]
dtype: object

In [149]:
z1 = [1,2,3,None,5]

s5 = pd.Series(z1)
print(s5)
print(sum(s5))

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64
nan

In [150]:
import numpy as np
s6 = pd.Series([1,2,3,np.nan,5])
print(s6)

s7 = pd.Series([1,2,3,4,5])
print(s7)

print(sum(s6))
print(sum(s7))

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64
0    1
1    2
2    3
3    4
4    5
dtype: int64
nan
15

In [151]:
d1 = pd.DataFrame(c2)
print(d1)

print(d1.index)
print(d1.columns)
print(d1.values)

d1.index=['학생1','학생2','학생3','학생4']
print(d1)

    name  age  point
0   Jane   34     80
1    Tom   24     70
2  Alice   51     90
3   Hong   45    100
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'point'], dtype='object')
[['Jane' 34 80]
 ['Tom' 24 70]
 ['Alice' 51 90]
 ['Hong' 45 100]]
      name  age  point
학생1   Jane   34     80
학생2    Tom   24     70
학생3  Alice   51     90
학생4   Hong   45    100

In [152]:
v1 = [['Jane',34,80],
      ['Tom',27,70],
      ['Alice',51,90],
      ['Hong',45,100]]
c1 = ['이름','나이','점수']
i1 = ['학생1','학생2','학생3','학생4']

df2 = pd.DataFrame(data=v1, columns=c1, index=i1)
df2

        이름  나이   점수
학생1   Jane  34   80
학생2    Tom  27   70
학생3  Alice  51   90
학생4   Hong  45  100

In [153]:
print(df2['이름'])

학생1     Jane
학생2      Tom
학생3    Alice
학생4     Hong
Name: 이름, dtype: object

In [154]:
print(df2.이름)

학생1     Jane
학생2      Tom
학생3    Alice
학생4     Hong
Name: 이름, dtype: object

In [155]:
df2[['이름','점수']]

        이름   점수
학생1   Jane   80
학생2    Tom   70
학생3  Alice   90
학생4   Hong  100

In [156]:
df2.iloc[1] # 결과값이 시리즈로 나옴

이름    Tom
나이     27
점수     70
Name: 학생2, dtype: object

In [157]:
df2.iloc[1:3, 1:]

     나이  점수
학생2  27  70
학생3  51  90

In [158]:
df2.loc['학생2']

이름    Tom
나이     27
점수     70
Name: 학생2, dtype: object

In [159]:
df2[1:3][['이름','나이']]

        이름  나이
학생2    Tom  27
학생3  Alice  51

In [160]:
df2.iloc[1:3][['이름','나이']]

        이름  나이
학생2    Tom  27
학생3  Alice  51

In [161]:
df2['학생2':'학생3'][['이름','나이']]

        이름  나이
학생2    Tom  27
학생3  Alice  51

In [162]:
print(df2.loc['학생1','점수'])
print(df2.loc['학생1':'학생3','점수'])
print(df2.loc['학생1':'학생3','나이':'점수'])
print(df2.loc['학생1':'학생3',:])
print(df2.loc[:,'나이':'점수'])

80
학생1    80
학생2    70
학생3    90
Name: 점수, dtype: int64
     나이  점수
학생1  34  80
학생2  27  70
학생3  51  90
        이름  나이  점수
학생1   Jane  34  80
학생2    Tom  27  70
학생3  Alice  51  90
     나이   점수
학생1  34   80
학생2  27   70
학생3  51   90
학생4  45  100

In [163]:
df2[df2['점수']>=90][['이름','나이']]

        이름  나이
학생3  Alice  51
학생4   Hong  45

In [164]:
cond = (df2['나이'] >50) & (df2['점수'] > 80)
df2[cond][['이름','점수']]

        이름  점수
학생3  Alice  90

In [165]:
df2.sort_values(by='점수', ascending=False)

        이름  나이   점수
학생4   Hong  45  100
학생3  Alice  51   90
학생1   Jane  34   80
학생2    Tom  27   70

In [166]:
df2['bonus'] = df2['나이']*df2['점수']/100
df2

        이름  나이   점수  bonus
학생1   Jane  34   80   27.2
학생2    Tom  27   70   18.9
학생3  Alice  51   90   45.9
학생4   Hong  45  100   45.0

In [167]:
import numpy as np
df2['empty'] = np.nan
df2

        이름  나이   점수  bonus  empty
학생1   Jane  34   80   27.2    NaN
학생2    Tom  27   70   18.9    NaN
학생3  Alice  51   90   45.9    NaN
학생4   Hong  45  100   45.0    NaN

In [168]:
# cond = df2['이름']=='Tom'

cond = df2['이름'].str.contains('Tom', na=False)
df2[cond]

      이름  나이  점수  bonus  empty
학생2  Tom  27  70   18.9    NaN

In [169]:
d3 = {'name':['Jane','Tom','Alice','John'],
      'age':[34,27,51,45],
      'point': [80,70,90,60]}

df3 = pd.DataFrame(d3,columns=['name','point','age','etc'], index=['학생1','학생2','학생3','학생4'])
df3
print(df3['point'].sum())
print(df3['point'].mean())
print(df3['point'].std())
print(df3['point'].var())
print(df3['point'].min())
print(df3['point'].max())

300
75.0
12.909944487358056
166.66666666666666
60
90

- Pandas

In [170]:
x = [['Jackson', 68, True, 1.5, 'A'],
     ['Liam', 74, True, 1.1, 'A'],
     ['Emma', 20, False, 0.89, 'C']]
df = pd.DataFrame(x, columns=['Name','Weight',"Option",'Etc','Type'])

print('type: ', type(df))
print('shape: ', df.shape)
print(df)

type:  <class 'pandas.core.frame.DataFrame'>
shape:  (3, 5)
      Name  Weight  Option   Etc Type
0  Jackson      68    True  1.50    A
1     Liam      74    True  1.10    A
2     Emma      20   False  0.89    C

In [171]:
data = {
    'Name':['Jackson','Emma','Noah','James'],
    'Weight':[68,75,77,78],
    'Option':[True,True,False,False],
    'Rate':[0.21,1.1,0.89,0.91],
    'Type':['A','A','C','C']
}
df = pd.DataFrame(data)

print('type: ', type(df))
print('shape: ', df.shape)
print(df)

type:  <class 'pandas.core.frame.DataFrame'>
shape:  (4, 5)
      Name  Weight  Option  Rate Type
0  Jackson      68    True  0.21    A
1     Emma      75    True  1.10    A
2     Noah      77   False  0.89    C
3    James      78   False  0.91    C

In [172]:
filename= '/content/drive/MyDrive/FLY AI/data/survey.csv'
df = pd.read_csv(filename)
df.head()

  sex  income  English  jobSatisfaction  stress
0   m    3000      500                5       5
1   f    4000      600                4       4
2   f    5000      700                3       2
3   m    6000      800                2       2
4   m    4000      700                2       5

In [173]:
import csv
f2 = open(filename, 'r')
new = csv.reader(f2)
d2=[]
for d in new:
  d2.append(d)
f2.close()
print(d2)

[['sex', 'income', 'English', 'jobSatisfaction', 'stress'], ['m', '3000', '500', '5', '5'], ['f', '4000', '600', '4', '4'], ['f', '5000', '700', '3', '2'], ['m', '6000', '800', '2', '2'], ['m', '4000', '700', '2', '5'], ['m', '3000', '600', '1', '5'], ['m', '3000', '500', '3', '1'], ['m', '5000', '500', '3', '2'], ['f', '4999', '600', '4', '3'], ['f', '5000', '700', '5', '4'], ['m', '3000', '500', '5', '5'], ['m', '4000', '600', '4', '4'], ['m', '5000', '700', '3', '2'], ['m', '6000', '800', '2', '5'], ['f', '4000', '700', '2', '4'], ['f', '3000', '600', '1', '2'], ['m', '3000', '500', '3', '2'], ['m', '5000', '500', '3', '5'], ['m', '4999', '600', '4', '5'], ['m', '5000', '500', '3', '1'], ['f', '4999', '600', '4', '2'], ['f', '5000', '700', '5', '3'], ['f', '3000', '500', '5', '4']]

In [174]:
df = pd.read_csv('https://raw.githubusercontent.com/devdio/flyai_datasets/refs/heads/main/iris.csv')
df.head()

   Sepal Length  Sepal Width  Petal Length  Petal Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

- 타이타닉 data

In [209]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/refs/heads/main/doc/data/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [210]:
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [193]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [213]:
df = pd.DataFrame({
'city': ['Busan', 'Busan', 'Busan', 'Busan',
    'Seoul', 'Seoul', 'Seoul'],
'fruits': ['Apple', 'Orange', 'Banana',
    'Banana', 'Apple', 'Apple', 'Banana'],
'price': [100, 200, 250, 300, 150, 200, 400],
'quantity': [1, 2, 3, 4, 5, 6, 7]
})

df

    city  fruits  price  quantity
0  Busan   Apple    100         1
1  Busan  Orange    200         2
2  Busan  Banana    250         3
3  Busan  Banana    300         4
4  Seoul   Apple    150         5
5  Seoul   Apple    200         6
6  Seoul  Banana    400         7

In [215]:
df.groupby('city')['price'].mean()

city
Busan    212.5
Seoul    250.0
Name: price, dtype: float64

In [217]:
df.groupby(['city','fruits']).mean(numeric_only=True)

              price  quantity
city  fruits
Busan Apple   100.0       1.0
      Banana  275.0       3.5
      Orange  200.0       2.0
Seoul Apple   175.0       5.5
      Banana  400.0       7.0

In [220]:
z = df['city'].map(lambda x: 'SEO' if x == 'Seoul' else 'BUS')
df['TAG'] = z
df

    city  fruits  price  quantity  TAG
0  Busan   Apple    100         1  BUS
1  Busan  Orange    200         2  BUS
2  Busan  Banana    250         3  BUS
3  Busan  Banana    300         4  BUS
4  Seoul   Apple    150         5  SEO
5  Seoul   Apple    200         6  SEO
6  Seoul  Banana    400         7  SEO

In [221]:
df['TAG'] = df['TAG'].map({'BUS':0, 'SEO':1})
df

    city  fruits  price  quantity  TAG
0  Busan   Apple    100         1    0
1  Busan  Orange    200         2    0
2  Busan  Banana    250         3    0
3  Busan  Banana    300         4    0
4  Seoul   Apple    150         5    1
5  Seoul   Apple    200         6    1
6  Seoul  Banana    400         7    1